server:
  port: 9090

spring:
  application:
    name: e.learning


  datasource:
    url: jdbc:postgresql://localhost:5432/e-learning-exercise
    username: admin
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
